version: '3'
services:
  api:
    image: node:12.18.4
    working_dir: /server
    environment: 
      - PGUSER=user
      - PGHOST=db
      - PGPASSWORD=habitpass
      - PGDATABASE=habit_test
      - PGPORT=5432
      - NODE_ENV=test
    depends_on:
      - db
    volumes:
      - type: bind
        source: ./
        target: /server
    command: bash -c "npm install && npm test"

  db:
    image: postgres:latest
    expose: 
      - "5432"
    volumes:
      - "test_dbdata:/var/lib/postgresql/data"
    environment: 
      - POSTGRES_DB=habit_test
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=habitpass
volumes:
  test_dbdata:
    